# Generated by Django 4.2.2 on 2023-06-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_tag_name"),
        ("project", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="tag",
            field=models.ManyToManyField(blank=True, to="user.tag"),
        ),
    ]
