# Generated by Django 4.2.2 on 2023-06-26 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(
                choices=[
                    ("python", "Python"),
                    ("java", "Java"),
                    ("javascript", "JavaScript"),
                    ("django", "Django"),
                    ("djangorestframework", "DjangoRestFramework"),
                    ("react", "React"),
                    ("api", "API"),
                ],
                max_length=25,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
