# Generated by Django 4.2.2 on 2023-07-05 19:04

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                null=True, upload_to=user.models.user_image_file_path
            ),
        ),
    ]
